export * from './results/Results';
export * from './chip/Chip';
export * from './hero/Hero';
export * from './parallax/Parallax';
export * from './card-results/CardResults';
export * from './wrapper-carousel/WrapperCarousel';
export * from './counter/Counter';
export * from './totalt-tests/TotalTests';
export * from './video-modal/VideoModal';